#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sanic_routing
Version  : 22.3.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/c3/72/e82be1d019e094f6b983bec9fee5ea512e8aaafe97b5346af2ba0e25cd56/sanic-routing-22.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c3/72/e82be1d019e094f6b983bec9fee5ea512e8aaafe97b5346af2ba0e25cd56/sanic-routing-22.3.0.tar.gz
Summary  : Core routing component for Sanic
Group    : Development/Tools
License  : MIT
Requires: pypi-sanic_routing-license = %{version}-%{release}
Requires: pypi-sanic_routing-python = %{version}-%{release}
Requires: pypi-sanic_routing-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Sanic Routing
## Background
Beginning in v21.3, Sanic makes use of this new AST-style router in two use cases:

%package license
Summary: license components for the pypi-sanic_routing package.
Group: Default

%description license
license components for the pypi-sanic_routing package.


%package python
Summary: python components for the pypi-sanic_routing package.
Group: Default
Requires: pypi-sanic_routing-python3 = %{version}-%{release}

%description python
python components for the pypi-sanic_routing package.


%package python3
Summary: python3 components for the pypi-sanic_routing package.
Group: Default
Requires: python3-core
Provides: pypi(sanic_routing)

%description python3
python3 components for the pypi-sanic_routing package.


%prep
%setup -q -n sanic-routing-22.3.0
cd %{_builddir}/sanic-routing-22.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648739206
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sanic_routing
cp %{_builddir}/sanic-routing-22.3.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sanic_routing/a37a1c39cd4fa4176ccd818a702e6f790735c3a5
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sanic_routing/a37a1c39cd4fa4176ccd818a702e6f790735c3a5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
