#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sanic_routing
Version  : 21.12.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/55/d6/7fa9b4adef9568e6d1bea3c0238f27a0f8407443a83498e9285b52b22522/sanic-routing-21.12.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/55/d6/7fa9b4adef9568e6d1bea3c0238f27a0f8407443a83498e9285b52b22522/sanic-routing-21.12.0.tar.gz
Summary  : Core routing component for Sanic
Group    : Development/Tools
License  : MIT
Requires: pypi-sanic_routing-python = %{version}-%{release}
Requires: pypi-sanic_routing-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Sanic Routing
## Background
Beginning in v21.3, Sanic makes use of this new AST-style router in two use cases:

%package python
Summary: python components for the pypi-sanic_routing package.
Group: Default
Requires: pypi-sanic_routing-python3 = %{version}-%{release}

%description python
python components for the pypi-sanic_routing package.


%package python3
Summary: python3 components for the pypi-sanic_routing package.
Group: Default
Requires: python3-core
Provides: pypi(sanic_routing)

%description python3
python3 components for the pypi-sanic_routing package.


%prep
%setup -q -n sanic-routing-21.12.0
cd %{_builddir}/sanic-routing-21.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641931953
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
